// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/tuplemapr.h"
#include <Rcpp.h>

using namespace Rcpp;

// link_hook
bool link_hook();
RcppExport SEXP _tuplemapr_link_hook() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(link_hook());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tuplemapr_link_hook", (DL_FUNC) &_tuplemapr_link_hook, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_tuplemapr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
