# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_map <- function() {
    invisible(.Call(`_tuplemapr_test_map`))
}

test_choose <- function() {
    invisible(.Call(`_tuplemapr_test_choose`))
}

